spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GCP_CLIENT_ID}
            client-secret: ${OAUTH_GCP_CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URL_PATH:http://localhost:8080}/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: openid,profile,email
            client-name: Google
            provider: google
          naver:
            client-id: ${OAUTH_NAVER_CLIENT_ID}
            client-secret: ${OAUTH_NAVER_CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URL_PATH:http://localhost:8080}/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Naver
            provider: naver
          kakao:
            client-id: ${OAUTH_KAKAO_CLIENT_ID}
            client-secret: ${OAUTH_KAKAO_CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URL_PATH:http://localhost:8080}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
#            scope: openid # oidc를 쓰려면 필수, 아니면 필요없음
            client-name: Kakao
            provider: kakao
          github: # github app을 쓰는 것을 추천
            client-id: ${OAUTH_GITHUB_CLIENT_ID}
            client-secret: ${OAUTH_GITHUB_CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URL_PATH:http://localhost:8080}/login/oauth2/code/github
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Github
            provider: github
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
            unlink-uri: https://oauth2.googleapis.com/revoke
            unlink-method: post
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: id
            unlink-uri:
            unlink-method:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            # oidc용 user-info-uri긴 한데... 안된다. 왜지?
#            user-info-uri: https://kapi.kakao.com/v1/oidc/userinfo
#            user-name-attribute: sub
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
            unlink-uri: https://kapi.kakao.com/v1/user/unlink
            unlink-method: post
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
            unlink-uri: https://api.github.com/applications/${OAUTH_GITHUB_CLIENT_ID}/token
            unlink-method: delete
