spring:
  application:
    name: oauth-practice

  config:
    import:
      - classpath:properties/aes-data.yaml
      - classpath:properties/mariadb.yaml
      - classpath:properties/oauth-provider.yaml
      - classpath:properties/redis.yaml